sudo: false
language: rust
rust:
- 1.24.0 # oldest supported version
- stable
- beta
- nightly

matrix:
  include:
  - env: RUSTFMT
    rust: 1.27.0  # `stable`: Locking down for consistent behavior
    install:
    - rustup component add rustfmt-preview
    script:
    - cargo fmt -- --write-mode=diff
  - env: RUSTFLAGS="-D warnings"
    rust: 1.27.0  # `stable`: Locking down for consistent behavior
    script:
    - cargo check --tests
  - env: CLIPPY
    rust: nightly-2018-07-17
    install:
      - rustup component add clippy-preview
    script:
      - cargo clippy --all-features -- -D clippy

install:
- rustc -Vv
- cargo -V

script:
- rm -rf target/debug/deps/*docmatic*  # Avoid link problems with cached versions
- cargo test --verbose
- cargo doc --no-deps

cache:
  cargo: true
